////////////////////////////////////////////////////////////////////////////////
//
// Generated by JavaToPas v1.4 20140515 - 182919
//
// Adapted to be usable by Brian Long (http://blong.com)
//
////////////////////////////////////////////////////////////////////////////////
unit Androidapi.JNI.Nfc;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.App,
  Androidapi.JNI.GraphicsContentViewText,
  Androidapi.JNI.Net,
  Androidapi.JNI.Os;

const
  TJNfcAdapterACTION_NDEF_DISCOVERED = 'android.nfc.action.NDEF_DISCOVERED';
  TJNfcAdapterACTION_TECH_DISCOVERED = 'android.nfc.action.TECH_DISCOVERED';
  TJNfcAdapterACTION_TAG_DISCOVERED = 'android.nfc.action.TAG_DISCOVERED';
  TJNfcAdapterEXTRA_TAG = 'android.nfc.extra.TAG';
  TJNfcAdapterEXTRA_NDEF_MESSAGES = 'android.nfc.extra.NDEF_MESSAGES';
  TJNfcAdapterEXTRA_ID = 'android.nfc.extra.ID';

  TJNdefRecordTNF_EMPTY = 0;
  TJNdefRecordTNF_WELL_KNOWN = 1;
  TJNdefRecordTNF_MIME_MEDIA = 2;
  TJNdefRecordTNF_ABSOLUTE_URI = 3;
  TJNdefRecordTNF_EXTERNAL_TYPE = 4;
  TJNdefRecordTNF_UNKNOWN = 5;
  TJNdefRecordTNF_UNCHANGED = 6;

type
  JNfcManager = interface;
  JNfcAdapter = interface;
  JNfcAdapter_CreateBeamUrisCallback = interface;
  JNfcAdapter_CreateNdefMessageCallback = interface;
  JNfcAdapter_OnNdefPushCompleteCallback = interface;
  JTag = interface;
  JNfcEvent = interface;
  JNdefMessage = interface;
  JNdefRecord = interface;

  JNfcManagerClass = interface(JObjectClass)
    ['{2D2927FF-A70B-4F1A-8CEC-AA85108D17EE}']
    function getDefaultAdapter : JNfcAdapter; cdecl;                            // ()Landroid/nfc/NfcAdapter; A: $1
  end;

  [JavaSignature('android/nfc/NfcManager')]
  JNfcManager = interface(JObject)
    ['{51D10989-1C94-4C11-AD2A-F8F9B29ADB18}']
    function getDefaultAdapter : JNfcAdapter; cdecl;                            // ()Landroid/nfc/NfcAdapter; A: $1
  end;

  TJNfcManager = class(TJavaGenericImport<JNfcManagerClass, JNfcManager>)
  end;

  JNfcAdapterClass = interface(JObjectClass)
    ['{576DB894-7A23-4125-ACBD-CFA8D236C90C}']
    function _GetACTION_NDEF_DISCOVERED : JString;                       //  A: $19
    function _GetACTION_TAG_DISCOVERED : JString;                         //  A: $19
    function _GetACTION_TECH_DISCOVERED : JString;                        //  A: $19
    function _GetEXTRA_ID : JString;                                      //  A: $19
    function _GetEXTRA_NDEF_MESSAGES : JString;                           //  A: $19
    function _GetEXTRA_TAG : JString;                                     //  A: $19
    function getDefaultAdapter(context : JContext) : JNfcAdapter; cdecl;        // (Landroid/content/Context;)Landroid/nfc/NfcAdapter; A: $9
    property ACTION_NDEF_DISCOVERED : JString read _GetACTION_NDEF_DISCOVERED;  // Ljava/lang/String; A: $19
    property ACTION_TAG_DISCOVERED : JString read _GetACTION_TAG_DISCOVERED;    // Ljava/lang/String; A: $19
    property ACTION_TECH_DISCOVERED : JString read _GetACTION_TECH_DISCOVERED;  // Ljava/lang/String; A: $19
    property EXTRA_ID : JString read _GetEXTRA_ID;                              // Ljava/lang/String; A: $19
    property EXTRA_NDEF_MESSAGES : JString read _GetEXTRA_NDEF_MESSAGES;        // Ljava/lang/String; A: $19
    property EXTRA_TAG : JString read _GetEXTRA_TAG;                            // Ljava/lang/String; A: $19
  end;

  [JavaSignature('android/nfc/NfcAdapter')]
  JNfcAdapter = interface(JObject)
    ['{1B95784D-3688-40C2-A805-9AFFFE9B2827}']
    function isEnabled : Boolean; cdecl;                                        // ()Z A: $1
    function isNdefPushEnabled : boolean; cdecl;                                // ()Z A: $1
    procedure disableForegroundDispatch(activity : JActivity) ; cdecl;          // (Landroid/app/Activity;)V A: $1
    procedure disableForegroundNdefPush(activity : JActivity) ; deprecated; cdecl;// (Landroid/app/Activity;)V A: $1
    // This method remains undeclared as parameter 4 is a 2D string
    // array, and the JNI Bridge doesn't support 2D arrays
    //procedure enableForegroundDispatch(activity : JActivity; intent : JPendingIntent; filters : TJavaObjectArray<JIntentFilter>; techLists : TJavaObjectBiArray<JString>) ; cdecl;// (Landroid/app/Activity;Landroid/app/PendingIntent;[Landroid/content/IntentFilter;[[Ljava/lang/String;)V A: $1
    procedure enableForegroundNdefPush(activity : JActivity; &message : JNdefMessage) ; deprecated; cdecl;// (Landroid/app/Activity;Landroid/nfc/NdefMessage;)V A: $1
    procedure setBeamPushUris(uris : TJavaObjectArray<Jnet_Uri>; activity : JActivity) ; cdecl;// ([Landroid/net/Uri;Landroid/app/Activity;)V A: $1
    procedure setBeamPushUrisCallback(callback : JNfcAdapter_CreateBeamUrisCallback; activity : JActivity) ; cdecl;// (Landroid/nfc/NfcAdapter$CreateBeamUrisCallback;Landroid/app/Activity;)V A: $1
    procedure setNdefPushMessage(&message : JNdefMessage; activity : JActivity; activities : TJavaObjectArray<JActivity>) ; cdecl;// (Landroid/nfc/NdefMessage;Landroid/app/Activity;[Landroid/app/Activity;)V A: $81
    procedure setNdefPushMessageCallback(callback : JNfcAdapter_CreateNdefMessageCallback; activity : JActivity; activities : TJavaObjectArray<JActivity>) ; cdecl;// (Landroid/nfc/NfcAdapter$CreateNdefMessageCallback;Landroid/app/Activity;[Landroid/app/Activity;)V A: $81
    procedure setOnNdefPushCompleteCallback(callback : JNfcAdapter_OnNdefPushCompleteCallback; activity : JActivity; activities : TJavaObjectArray<JActivity>) ; cdecl;// (Landroid/nfc/NfcAdapter$OnNdefPushCompleteCallback;Landroid/app/Activity;[Landroid/app/Activity;)V A: $81
  end;

  TJNfcAdapter = class(TJavaGenericImport<JNfcAdapterClass, JNfcAdapter>)
  end;

  JNfcAdapter_CreateBeamUrisCallbackClass = interface(JObjectClass)
    ['{6F399C75-107B-435D-BBE1-D4F32657E2D2}']
  end;

  [JavaSignature('android/nfc/NfcAdapter_CreateBeamUrisCallback')]
  JNfcAdapter_CreateBeamUrisCallback = interface(JObject)
    ['{507DA3B6-98EE-4496-BA90-EA452A4993F5}']
    function createBeamUris(JNfcEventparam0 : JNfcEvent) : TJavaObjectArray<Jnet_Uri>; cdecl;// (Landroid/nfc/NfcEvent;)[Landroid/net/Uri; A: $401
  end;

  TJNfcAdapter_CreateBeamUrisCallback = class(TJavaGenericImport<JNfcAdapter_CreateBeamUrisCallbackClass, JNfcAdapter_CreateBeamUrisCallback>)
  end;

  JNfcAdapter_CreateNdefMessageCallbackClass = interface(JObjectClass)
    ['{CAB6845C-87EE-43E8-9114-4CD028E4F023}']
  end;

  [JavaSignature('android/nfc/NfcAdapter_CreateNdefMessageCallback')]
  JNfcAdapter_CreateNdefMessageCallback = interface(JObject)
    ['{40E88317-43A2-44F3-8E5F-8701EFC7F88E}']
    function createNdefMessage(JNfcEventparam0 : JNfcEvent) : JNdefMessage; cdecl;// (Landroid/nfc/NfcEvent;)Landroid/nfc/NdefMessage; A: $401
  end;

  TJNfcAdapter_CreateNdefMessageCallback = class(TJavaGenericImport<JNfcAdapter_CreateNdefMessageCallbackClass, JNfcAdapter_CreateNdefMessageCallback>)
  end;

  JNfcAdapter_OnNdefPushCompleteCallbackClass = interface(JObjectClass)
    ['{329A1391-1B3A-44D4-A180-7B8CC355E274}']
  end;

  [JavaSignature('android/nfc/NfcAdapter_OnNdefPushCompleteCallback')]
  JNfcAdapter_OnNdefPushCompleteCallback = interface(JObject)
    ['{D58424EE-F0FC-4CE0-983C-D654EE99CEC7}']
    procedure onNdefPushComplete(JNfcEventparam0 : JNfcEvent) ; cdecl;          // (Landroid/nfc/NfcEvent;)V A: $401
  end;

  TJNfcAdapter_OnNdefPushCompleteCallback = class(TJavaGenericImport<JNfcAdapter_OnNdefPushCompleteCallbackClass, JNfcAdapter_OnNdefPushCompleteCallback>)
  end;

  JTagClass = interface(JObjectClass)
    ['{FF9E927B-3CBC-44E1-9CE1-47247AEEBA44}']
    function _GetCREATOR : JParcelable_Creator; cdecl;                          //  A: $19
    property CREATOR : JParcelable_Creator read _GetCREATOR;                    // Landroid/os/Parcelable$Creator; A: $19
  end;

  [JavaSignature('android/nfc/Tag')]
  JTag = interface(JObject)
    ['{D1CB91EF-94C4-4930-BCEF-A0A6C6712C0E}']
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function getId : TJavaArray<Byte>; cdecl;                                   // ()[B A: $1
    function getTechList : TJavaObjectArray<JString>; cdecl;                          // ()[Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure writeToParcel(dest : JParcel; flags : Integer) ; cdecl;           // (Landroid/os/Parcel;I)V A: $1
  end;

  TJTag = class(TJavaGenericImport<JTagClass, JTag>)
  end;

  JNfcEventClass = interface(JObjectClass)
    ['{83E040AF-F429-4B7E-839D-FCD116332D9F}']
    function _GetnfcAdapter : JNfcAdapter; cdecl;                               //  A: $11
    property nfcAdapter : JNfcAdapter read _GetnfcAdapter;                      // Landroid/nfc/NfcAdapter; A: $11
  end;

  [JavaSignature('android/nfc/NfcEvent')]
  JNfcEvent = interface(JObject)
    ['{F96B51E7-47F6-4195-9209-730D8088D8FD}']
  end;

  TJNfcEvent = class(TJavaGenericImport<JNfcEventClass, JNfcEvent>)
  end;

  JNdefMessageClass = interface(JObjectClass)
    ['{7CE2D708-6436-4C46-96A7-604C86828B27}']
    function _GetCREATOR : JParcelable_Creator; cdecl;                          //  A: $19
    function init(&record : JNdefRecord; records : TJavaObjectArray<JNdefRecord>) : JNdefMessage; cdecl; overload;// (Landroid/nfc/NdefRecord;[Landroid/nfc/NdefRecord;)V A: $81
    function init(data : TJavaArray<Byte>) : JNdefMessage; cdecl; overload;     // ([B)V A: $1
    function init(records : TJavaObjectArray<JNdefRecord>) : JNdefMessage; cdecl; overload;// ([Landroid/nfc/NdefRecord;)V A: $1
    property CREATOR : JParcelable_Creator read _GetCREATOR;                    // Landroid/os/Parcelable$Creator; A: $19
  end;

  [JavaSignature('android/nfc/NdefMessage')]
  JNdefMessage = interface(JObject)
    ['{186B19E4-8AA0-41AA-ABB9-85D2C1C4D487}']
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function equals(obj : JObject) : boolean; cdecl;                            // (Ljava/lang/Object;)Z A: $1
    function getByteArrayLength : Integer; cdecl;                               // ()I A: $1
    function getRecords : TJavaObjectArray<JNdefRecord>; cdecl;                       // ()[Landroid/nfc/NdefRecord; A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function toByteArray : TJavaArray<Byte>; cdecl;                             // ()[B A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure writeToParcel(dest : JParcel; flags : Integer) ; cdecl;           // (Landroid/os/Parcel;I)V A: $1
  end;

  TJNdefMessage = class(TJavaGenericImport<JNdefMessageClass, JNdefMessage>)
  end;

  JNdefRecordClass = interface(JObjectClass)
    ['{1A923B8C-925A-4E62-BB42-954F780F2C73}']
    function _GetCREATOR : JParcelable_Creator; cdecl;                          //  A: $19
    function _GetRTD_ALTERNATIVE_CARRIER : TJavaArray<Byte>; cdecl;             //  A: $19
    function _GetRTD_HANDOVER_CARRIER : TJavaArray<Byte>; cdecl;                //  A: $19
    function _GetRTD_HANDOVER_REQUEST : TJavaArray<Byte>; cdecl;                //  A: $19
    function _GetRTD_HANDOVER_SELECT : TJavaArray<Byte>; cdecl;                 //  A: $19
    function _GetRTD_SMART_POSTER : TJavaArray<Byte>; cdecl;                    //  A: $19
    function _GetRTD_TEXT : TJavaArray<Byte>; cdecl;                            //  A: $19
    function _GetRTD_URI : TJavaArray<Byte>; cdecl;                             //  A: $19
    function _GetTNF_ABSOLUTE_URI : SmallInt; cdecl;                            //  A: $19
    function _GetTNF_EMPTY : SmallInt; cdecl;                                   //  A: $19
    function _GetTNF_EXTERNAL_TYPE : SmallInt; cdecl;                           //  A: $19
    function _GetTNF_MIME_MEDIA : SmallInt; cdecl;                              //  A: $19
    function _GetTNF_UNCHANGED : SmallInt; cdecl;                               //  A: $19
    function _GetTNF_UNKNOWN : SmallInt; cdecl;                                 //  A: $19
    function _GetTNF_WELL_KNOWN : SmallInt; cdecl;                              //  A: $19
    function createApplicationRecord(packageName : JString) : JNdefRecord; cdecl;// (Ljava/lang/String;)Landroid/nfc/NdefRecord; A: $9
    function createExternal(domain : JString; &type : JString; data : TJavaArray<Byte>) : JNdefRecord; cdecl;// (Ljava/lang/String;Ljava/lang/String;[B)Landroid/nfc/NdefRecord; A: $9
    function createMime(mimeType : JString; mimeData : TJavaArray<Byte>) : JNdefRecord; cdecl;// (Ljava/lang/String;[B)Landroid/nfc/NdefRecord; A: $9
    function createUri(uri : Jnet_Uri) : JNdefRecord; cdecl; overload;              // (Landroid/net/Uri;)Landroid/nfc/NdefRecord; A: $9
    function createUri(uriString : JString) : JNdefRecord; cdecl; overload;     // (Ljava/lang/String;)Landroid/nfc/NdefRecord; A: $9
    function init(data : TJavaArray<Byte>) : JNdefRecord; deprecated; cdecl; overload;// ([B)V A: $1
    function init(tnf : SmallInt; &type : TJavaArray<Byte>; id : TJavaArray<Byte>; payload : TJavaArray<Byte>) : JNdefRecord; cdecl; overload;// (S[B[B[B)V A: $1
    property CREATOR : JParcelable_Creator read _GetCREATOR;                    // Landroid/os/Parcelable$Creator; A: $19
    property RTD_ALTERNATIVE_CARRIER : TJavaArray<Byte> read _GetRTD_ALTERNATIVE_CARRIER;// [B A: $19
    property RTD_HANDOVER_CARRIER : TJavaArray<Byte> read _GetRTD_HANDOVER_CARRIER;// [B A: $19
    property RTD_HANDOVER_REQUEST : TJavaArray<Byte> read _GetRTD_HANDOVER_REQUEST;// [B A: $19
    property RTD_HANDOVER_SELECT : TJavaArray<Byte> read _GetRTD_HANDOVER_SELECT;// [B A: $19
    property RTD_SMART_POSTER : TJavaArray<Byte> read _GetRTD_SMART_POSTER;     // [B A: $19
    property RTD_TEXT : TJavaArray<Byte> read _GetRTD_TEXT;                     // [B A: $19
    property RTD_URI : TJavaArray<Byte> read _GetRTD_URI;                       // [B A: $19
    property TNF_ABSOLUTE_URI : SmallInt read _GetTNF_ABSOLUTE_URI;             // S A: $19
    property TNF_EMPTY : SmallInt read _GetTNF_EMPTY;                           // S A: $19
    property TNF_EXTERNAL_TYPE : SmallInt read _GetTNF_EXTERNAL_TYPE;           // S A: $19
    property TNF_MIME_MEDIA : SmallInt read _GetTNF_MIME_MEDIA;                 // S A: $19
    property TNF_UNCHANGED : SmallInt read _GetTNF_UNCHANGED;                   // S A: $19
    property TNF_UNKNOWN : SmallInt read _GetTNF_UNKNOWN;                       // S A: $19
    property TNF_WELL_KNOWN : SmallInt read _GetTNF_WELL_KNOWN;                 // S A: $19
  end;

  [JavaSignature('android/nfc/NdefRecord')]
  JNdefRecord = interface(JObject)
    ['{9A055F41-0D6F-4833-AE58-4043EBCF7BD8}']
    function describeContents : Integer; cdecl;                                 // ()I A: $1
    function equals(obj : JObject) : boolean; cdecl;                            // (Ljava/lang/Object;)Z A: $1
    function getId : TJavaArray<Byte>; cdecl;                                   // ()[B A: $1
    function getPayload : TJavaArray<Byte>; cdecl;                              // ()[B A: $1
    function getTnf : SmallInt; cdecl;                                          // ()S A: $1
    function getType : TJavaArray<Byte>; cdecl;                                 // ()[B A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function toByteArray : TJavaArray<Byte>; deprecated; cdecl;                 // ()[B A: $1
    function toMimeType : JString; cdecl;                                       // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function toUri : Jnet_Uri; cdecl;                                               // ()Landroid/net/Uri; A: $1
    procedure writeToParcel(dest : JParcel; flags : Integer) ; cdecl;           // (Landroid/os/Parcel;I)V A: $1
  end;

  TJNdefRecord = class(TJavaGenericImport<JNdefRecordClass, JNdefRecord>)
  end;

implementation

uses
  FMX.Types;

procedure RegisterTypes;
begin
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JNfcAdapter', TypeInfo(Androidapi.JNI.Nfc.JNfcAdapter));
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JNfcAdapter_CreateBeamUrisCallback',
    TypeInfo(Androidapi.JNI.Nfc.JNfcAdapter_CreateBeamUrisCallback));
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JNfcAdapter_CreateNdefMessageCallback',
    TypeInfo(Androidapi.JNI.Nfc.JNfcAdapter_CreateNdefMessageCallback));
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JNfcAdapter_OnNdefPushCompleteCallback',
    TypeInfo(Androidapi.JNI.Nfc.JNfcAdapter_OnNdefPushCompleteCallback));
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JTag', TypeInfo(Androidapi.JNI.Nfc.JTag));
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JNfcEvent', TypeInfo(Androidapi.JNI.Nfc.JNfcEvent));
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JNdefMessage', TypeInfo(Androidapi.JNI.Nfc.JNdefMessage));
  TRegTypes.RegisterType('Androidapi.JNI.Nfc.JNdefRecord', TypeInfo(Androidapi.JNI.Nfc.JNdefRecord));
end;

initialization
  RegisterTypes;
end.
