/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.twitter.sdk.android.core;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int tw__blue_default=0x7f040001;
        public static final int tw__blue_pressed=0x7f040002;
        public static final int tw__light_gray=0x7f040003;
        public static final int tw__solid_white=0x7f040004;
    }
    public static final class dimen {
        public static final int tw__login_btn_drawable_padding=0x7f070000;
        public static final int tw__login_btn_height=0x7f070001;
        public static final int tw__login_btn_left_padding=0x7f070002;
        public static final int tw__login_btn_radius=0x7f070005;
        public static final int tw__login_btn_right_padding=0x7f070003;
        public static final int tw__login_btn_text_size=0x7f070004;
    }
    public static final class drawable {
        public static final int tw__ic_logo_default=0x7f020004;
        public static final int tw__login_btn=0x7f020005;
        public static final int tw__login_btn_default=0x7f020006;
        public static final int tw__login_btn_disabled=0x7f020007;
        public static final int tw__login_btn_pressed=0x7f020008;
    }
    public static final class id {
        public static final int tw__spinner=0x7f080001;
        public static final int tw__web_view=0x7f080000;
    }
    public static final class layout {
        public static final int tw__activity_oauth=0x7f030000;
    }
    public static final class string {
        public static final int tw__login_btn_txt=0x7f060000;
    }
    public static final class style {
    }
}
