/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.huawei.hms.ml.camera;

public final class R {
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>top</code></td><td>0</td><td></td></tr>
<tr><td><code>bottom</code></td><td>1</td><td></td></tr>
</table>
         */
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>line</code></td><td>1</td><td></td></tr>
<tr><td><code>grid</code></td><td>2</td><td></td></tr>
</table>
         */
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
    }
    public static final class color {
    }
    public static final class drawable {
    }
    public static final class id {
        public static final int mlkit_camera_auto_focus=0x7f070000;
        public static final int mlkit_camera_ha_quit=0x7f070001;
        public static final int mlkit_camera_picture_ha_begin=0x7f070002;
        public static final int mlkit_camera_picture_ha_end=0x7f070003;
        public static final int mlkit_camera_preview_ha_begin=0x7f070004;
        public static final int mlkit_camera_preview_ha_end=0x7f070005;
    }
    public static final class layout {
    }
    public static final class string {
    }
    public static final class style {
    }
    public static final class styleable {
        /** Attributes that can be used with a ViewfinderView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_cornerColor com.huawei.hms.ml.camera:scankit_cornerColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_frameColor com.huawei.hms.ml.camera:scankit_frameColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_frameHeight com.huawei.hms.ml.camera:scankit_frameHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_frameWidth com.huawei.hms.ml.camera:scankit_frameWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_gridColumn com.huawei.hms.ml.camera:scankit_gridColumn}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_gridHeight com.huawei.hms.ml.camera:scankit_gridHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_labelText com.huawei.hms.ml.camera:scankit_labelText}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_labelTextColor com.huawei.hms.ml.camera:scankit_labelTextColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_labelTextLocation com.huawei.hms.ml.camera:scankit_labelTextLocation}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_labelTextPadding com.huawei.hms.ml.camera:scankit_labelTextPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_labelTextSize com.huawei.hms.ml.camera:scankit_labelTextSize}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_laserColor com.huawei.hms.ml.camera:scankit_laserColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_laserStyle com.huawei.hms.ml.camera:scankit_laserStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_maskColor com.huawei.hms.ml.camera:scankit_maskColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_resultPointColor com.huawei.hms.ml.camera:scankit_resultPointColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_showResultPoint com.huawei.hms.ml.camera:scankit_showResultPoint}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_titleColor com.huawei.hms.ml.camera:scankit_titleColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewfinderView_scankit_titleSize com.huawei.hms.ml.camera:scankit_titleSize}</code></td><td></td></tr>
           </table>
           @see #ViewfinderView_scankit_cornerColor
           @see #ViewfinderView_scankit_frameColor
           @see #ViewfinderView_scankit_frameHeight
           @see #ViewfinderView_scankit_frameWidth
           @see #ViewfinderView_scankit_gridColumn
           @see #ViewfinderView_scankit_gridHeight
           @see #ViewfinderView_scankit_labelText
           @see #ViewfinderView_scankit_labelTextColor
           @see #ViewfinderView_scankit_labelTextLocation
           @see #ViewfinderView_scankit_labelTextPadding
           @see #ViewfinderView_scankit_labelTextSize
           @see #ViewfinderView_scankit_laserColor
           @see #ViewfinderView_scankit_laserStyle
           @see #ViewfinderView_scankit_maskColor
           @see #ViewfinderView_scankit_resultPointColor
           @see #ViewfinderView_scankit_showResultPoint
           @see #ViewfinderView_scankit_titleColor
           @see #ViewfinderView_scankit_titleSize
         */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_cornerColor}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_cornerColor
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_frameColor}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_frameColor
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_frameHeight}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_frameHeight
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_frameWidth}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_frameWidth
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_gridColumn}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_gridColumn
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_gridHeight}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_gridHeight
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_labelText}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_labelText
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_labelTextColor}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_labelTextColor
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_labelTextLocation}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>top</code></td><td>0</td><td></td></tr>
<tr><td><code>bottom</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.huawei.hms.ml.camera:scankit_labelTextLocation
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_labelTextPadding}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_labelTextPadding
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_labelTextSize}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_labelTextSize
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_laserColor}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_laserColor
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_laserStyle}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>line</code></td><td>1</td><td></td></tr>
<tr><td><code>grid</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.huawei.hms.ml.camera:scankit_laserStyle
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_maskColor}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_maskColor
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_resultPointColor}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_resultPointColor
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_showResultPoint}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_showResultPoint
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_titleColor}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_titleColor
        */
        /**
          <p>This symbol is the offset where the {@link com.huawei.hms.ml.camera.R.attr#scankit_titleSize}
          attribute's value can be found in the {@link #ViewfinderView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.huawei.hms.ml.camera:scankit_titleSize
        */
    };
}
