post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end

use_frameworks!
inhibit_all_warnings!

target ‘PrinterDemo’ do
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'MJExtension'
pod 'SwiftyJSON'
pod 'MJRefresh'
pod 'SnapKit'
pod 'Reusable'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'Then'

end
