/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.qq.e;

public final class R {
    public static final class anim {
        public static final int slide_right_in=0x7f030000;
        public static final int slide_up=0x7f030001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int notification_accent_color=0x7f050000;
    }
    public static final class drawable {
        public static final int gdt_ic_back=0x7f020000;
        public static final int gdt_ic_browse=0x7f020001;
        public static final int gdt_ic_download=0x7f020002;
        public static final int gdt_ic_enter_fullscreen=0x7f020003;
        public static final int gdt_ic_exit_fullscreen=0x7f020004;
        public static final int gdt_ic_express_back_to_port=0x7f020005;
        public static final int gdt_ic_express_close=0x7f020006;
        public static final int gdt_ic_express_enter_fullscreen=0x7f020007;
        public static final int gdt_ic_express_pause=0x7f020008;
        public static final int gdt_ic_express_play=0x7f020009;
        public static final int gdt_ic_express_volume_off=0x7f02000a;
        public static final int gdt_ic_express_volume_on=0x7f02000b;
        public static final int gdt_ic_native_back=0x7f02000c;
        public static final int gdt_ic_native_download=0x7f02000d;
        public static final int gdt_ic_native_volume_off=0x7f02000e;
        public static final int gdt_ic_native_volume_on=0x7f02000f;
        public static final int gdt_ic_pause=0x7f020010;
        public static final int gdt_ic_play=0x7f020011;
        public static final int gdt_ic_progress_thumb_normal=0x7f020012;
        public static final int gdt_ic_replay=0x7f020013;
        public static final int gdt_ic_seekbar_background=0x7f020014;
        public static final int gdt_ic_seekbar_progress=0x7f020015;
        public static final int gdt_ic_video_detail_close=0x7f020016;
        public static final int gdt_ic_volume_off=0x7f020017;
        public static final int gdt_ic_volume_on=0x7f020018;
        public static final int ic_launcher=0x7f020019;
        public static final int ic_notification=0x7f02001a;
        public static final int splash_image=0x7f02001b;
        public static final int splash_image_def=0x7f02001c;
    }
    public static final class integer {
        public static final int min_screen_width_bucket=0x7f070000;
    }
    public static final class string {
        public static final int app_name=0x7f080000;
    }
    public static final class style {
        public static final int AppTheme=0x7f060000;
        public static final int DialogAnimationRight=0x7f060001;
        public static final int DialogAnimationUp=0x7f060002;
        public static final int DialogFullScreen=0x7f060003;
    }
    public static final class xml {
        public static final int gdt_file_path=0x7f040000;
    }
}
